### ISSUE TITLE
Why the game doesn't end?

### ISSUE THREAD

**Issue by trollodel** [Samuot01/RedPepper#13]
![immagine](https://user-images.githubusercontent.com/33117082/37254189-294b008c-253b-11e8-92ef-3d87cec7d5d7.png)
I find the word, but the game still continue, please fix it.

**Comment by Samuot01** [comment]
we you arrive at this point you need to enter in ("Inserisci parola") and type the word on top

**Comment by creeloper27** [comment]
it doesn't end for me
