### ISSUE TITLE
Bad identation

### ISSUE THREAD

**Issue by trollodel** [Samuot01/RedPepper#3]
Identation is incorrect in some parts of code, please ident **better**

**Comment by Friedchicken01** [comment]
And don't try to use **spaces** for that, use tabs

**Comment by Samuot01** [comment]
thanks Users Friedchicken01 and Trollodel. The Software House is alredy employ for the indentation fixes. I will hope this problem will fixed in 2-3 working days .
I will send you a tryed version for see if you like this Fixes. Tell me if you enjoy!
